name: Mark Tasks Overdue
on:
  schedule:
    - cron: '*/55 * * * *'
  workflow_dispatch:

jobs:
  label-issues:
    name: Label issues with due dates
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Run Due Dates action
        uses: ./
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
